version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Installing composer dependencies
      - composer install --quiet

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Generating application key
      - cp .env.example .env
      - php artisan key:generate
      - echo Performing static analysis level 1
      - php artisan code:analyse --level=1
      - echo Reviewing code standards
      - ./vendor/bin/phpcs
      - echo Reviewing unit tests
      - ./vendor/bin/phpunit
