version: '3.6'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
        - .:/usr/src/app
        - ./docker/config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
  php:
    image: mirdrack/monica-php:latest
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: monicadb
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8000:80
    expose:
      - 80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: on-failure
    networks:
      - default

networks:
  default:
    external:
      name: monica-network
